# Generated by Django 4.0.6 on 2022-07-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='name')),
                ('anons', models.CharField(max_length=200, verbose_name='anons')),
                ('text', models.TextField(verbose_name='full_text')),
                ('date', models.DateField(verbose_name='Date')),
            ],
        ),
    ]
