# Generated by Django 4.0.6 on 2022-07-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticles',
            options={'verbose_name': 'News article', 'verbose_name_plural': 'News articles'},
        ),
        migrations.RemoveField(
            model_name='newsarticles',
            name='anons',
        ),
        migrations.AddField(
            model_name='newsarticles',
            name='announcement',
            field=models.CharField(default='none', max_length=200, verbose_name='announcement'),
        ),
    ]
