# Generated by Django 4.0.6 on 2022-07-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticles_options_remove_newsarticles_anons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticles',
            name='announcement',
        ),
    ]
