# Generated by Django 4.0.6 on 2022-08-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_newsarticles_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text="Enter author's name", max_length=100, verbose_name="The author's name")),
                ('date_of_registration', models.CharField(blank=True, help_text='Enter date of registration', max_length=20, null=True, verbose_name='Date of registration')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the article's rubric", max_length=150, verbose_name="The article's rubric")),
            ],
        ),
        migrations.AddField(
            model_name='newsarticles',
            name='author',
            field=models.ForeignKey(help_text='Select the author', null=True, on_delete=django.db.models.deletion.PROTECT, to='news.author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='newsarticles',
            name='rubric',
            field=models.ForeignKey(help_text='Choose the rubric', null=True, on_delete=django.db.models.deletion.PROTECT, to='news.rubric', verbose_name='Rubric'),
        ),
    ]
