# Generated by Django 4.0.6 on 2022-08-08 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_remove_author_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_registration',
            field=models.CharField(blank=True, help_text='Enter date of registration', max_length=20, null=True, verbose_name='Date of registration'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='newsarticles',
            name='author',
            field=models.ForeignKey(help_text='Select the author', null=True, on_delete=django.db.models.deletion.PROTECT, to='news.author', verbose_name='Author'),
        ),
    ]
