# Generated by Django 4.0.6 on 2022-08-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_author_date_of_registration_alter_author_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(blank=True, help_text="Enter author's name", max_length=100, null=True, verbose_name="The author's name"),
        ),
    ]
