# Generated by Django 4.0.6 on 2022-08-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_author_author_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
