# Generated by Django 4.0.6 on 2022-10-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsarticles_photo_alter_newsarticles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticles',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='newsarticles',
            name='text',
            field=models.TextField(verbose_name='Full_text'),
        ),
        migrations.AlterField(
            model_name='newsarticles',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
