# Generated by Django 4.0.6 on 2022-11-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsarticles_views_alter_newsarticles_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticles',
            name='slug',
            field=models.SlugField(default=0, max_length=255, verbose_name='Url'),
        ),
    ]
