# Generated by Django 4.0.6 on 2022-11-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newsarticles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Url'),
        ),
    ]
